# Generated by Django 3.1.2 on 2020-10-25 07:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='division', on_delete=django.db.models.deletion.CASCADE, to='dashboard.district'),
        ),
    ]
