# Generated by Django 3.1.1 on 2020-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draf', 'Draft'), ('published', 'Publish Now')], default='draft', max_length=12),
        ),
    ]
