# Generated by Django 3.1.1 on 2020-11-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Publish Now')], default='draft', max_length=12),
        ),
    ]
