# Generated by Django 3.1.1 on 2020-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20201109_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Publish Now'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='notice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
