# Generated by Django 3.1.2 on 2020-10-25 07:36

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='division', chained_model_field='division', on_delete=django.db.models.deletion.CASCADE, to='school.district'),
        ),
        migrations.AlterField(
            model_name='school',
            name='union',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='upazila', chained_model_field='upazila', on_delete=django.db.models.deletion.CASCADE, to='school.union'),
        ),
        migrations.AlterField(
            model_name='school',
            name='upazila',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, to='school.upazila'),
        ),
    ]
