# Generated by Django 3.1.2 on 2020-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201025_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
