# Generated by Django 3.1.1 on 2020-11-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201029_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': '   Districts'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name_plural': '    Divisions'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'verbose_name_plural': ' Unions'},
        ),
        migrations.AlterModelOptions(
            name='upazila',
            options={'verbose_name_plural': '  Upazilas'},
        ),
    ]
