# Generated by Django 3.1.1 on 2020-11-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_historicalschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSchool',
        ),
    ]
