# Generated by Django 3.1.4 on 2020-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activenode',
            name='class_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
