# Generated by Django 3.1.1 on 2020-11-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_historicalteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTeacher',
        ),
    ]
