# Generated by Django 3.1.1 on 2020-11-02 05:31

import apps.course_material.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': ' Chapters',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': '   Classes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_material.class')),
            ],
            options={
                'verbose_name_plural': '  Subjects',
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(unique=True, upload_to=apps.course_material.models.content_file_name)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_material.class')),
                ('chapter', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, to='course_material.chapter')),
                ('subject', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='_class', chained_model_field='_class', on_delete=django.db.models.deletion.CASCADE, to='course_material.subject')),
            ],
            options={
                'verbose_name_plural': 'CourseMeterials',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_material.class'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_material.subject'),
        ),
    ]
