# Generated by Django 3.1.1 on 2020-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='_class',
        ),
        migrations.AddField(
            model_name='chapter',
            name='_class',
            field=models.ManyToManyField(to='course_material.Class'),
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(to='course_material.Subject'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='_class',
        ),
        migrations.AddField(
            model_name='subject',
            name='_class',
            field=models.ManyToManyField(to='course_material.Class'),
        ),
    ]
