# Generated by Django 3.1.1 on 2020-11-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '3. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': '1. Classes'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name_plural': '4. CourseMeterials'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '2. Subjects'},
        ),
    ]
