# Generated by Django 3.1.4 on 2020-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0002_auto_20201202_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='unit_name',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
