# Generated by Django 3.1.1 on 2020-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0002_auto_20201101_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': ' Chapters'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': '   Classes'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name_plural': 'CourseMeterials'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '  Subjects'},
        ),
    ]
