# Generated by Django 3.1.1 on 2020-11-01 10:50

import apps.course_material.models
from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0003_auto_20201101_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='content',
            field=smartfields.fields.FileField(upload_to=apps.course_material.models.content_file_name),
        ),
    ]
