# Generated by Django 3.1.1 on 2020-11-01 10:54

import apps.course_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0004_auto_20201101_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='content',
            field=models.FileField(upload_to=apps.course_material.models.content_file_name),
        ),
    ]
