# Generated by Django 3.1.1 on 2020-11-01 11:01

import apps.course_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0005_auto_20201101_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='content',
            field=models.FileField(unique=True, upload_to=apps.course_material.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
