# Generated by Django 3.1.1 on 2020-11-03 06:00

import apps.course_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0006_auto_20201103_0557'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursematerial',
            name='unique content',
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='content',
            field=models.FileField(upload_to=apps.course_material.models.content_file_name),
        ),
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.UniqueConstraint(fields=('class_name', 'subject', 'chapter'), name='unique content'),
        ),
    ]
