# Generated by Django 3.1.1 on 2020-11-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0007_auto_20201103_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='title',
            field=models.TextField(default='rahi chowdory'),
            preserve_default=False,
        ),
    ]
