# Generated by Django 3.1.1 on 2020-11-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0008_coursematerial_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-created'], 'verbose_name_plural': 'CourseMeterials'},
        ),
    ]
