# Generated by Django 3.1.4 on 2020-12-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_material', '0001_initial'),
        ('school', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('school_name', models.CharField(max_length=100)),

                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='disable', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course_material.class')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
